wandb_version: 1

temp_tau:
  desc: null
  value: 0.12
edge_drop_prob:
  desc: null
  value: 0.1
latent_dim_rec:
  desc: null
  value: 64
num_layers:
  desc: null
  value: 3
if_pretrain:
  desc: null
  value: 0
dataset:
  desc: null
  value: gowalla
lr:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 0.0001
seed:
  desc: null
  value: 2023
model:
  desc: null
  value: LightGCN
if_load_embedding:
  desc: null
  value: 0
if_tensorboard:
  desc: null
  value: 1
epochs:
  desc: null
  value: 1000
if_multicore:
  desc: null
  value: 1
early_stop_steps:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 2048
lambda1:
  desc: null
  value: 0.1
topks:
  desc: null
  value:
  - 20
  - 40
test_u_batch_size:
  desc: null
  value: 2048
pop_group:
  desc: null
  value: 10
if_big_matrix:
  desc: null
  value: 0
n_fold:
  desc: null
  value: 2
p_drop:
  desc: null
  value: 0.1
perplexity:
  desc: null
  value: 50
visual_epoch:
  desc: null
  value: 3
if_double_label:
  desc: null
  value: 1
if_tsne:
  desc: null
  value: 1
tsne_group:
  desc: null
  value:
  - 0
  - 9
eps_SimGCL:
  desc: null
  value: 0.1
init_method:
  desc: null
  value: Normal
tsne_points:
  desc: null
  value: 2000
loss:
  desc: null
  value: Adaptive
augment:
  desc: null
  value: 'No'
alpha:
  desc: null
  value: 0.5
epoch_only_pop_for_BCloss:
  desc: null
  value: 5
centroid_mode:
  desc: null
  value: eigenvector
commonNeighbor_mode:
  desc: null
  value: SC
n_cluster:
  desc: null
  value: 10
sigma_gausse:
  desc: null
  value: 1.0
adaptive_method:
  desc: null
  value: mlp
epsilon_GCLRec:
  desc: null
  value: 0.1
w_GCLRec:
  desc: null
  value: 0.1
k_aug:
  desc: null
  value: 0
if_visual:
  desc: null
  value: 0
GTN_K:
  desc: null
  value: 3
GTN_alpha:
  desc: null
  value: 0.3
if_SVD:
  desc: null
  value: 1
svd_q:
  desc: null
  value: 5
tau_plus:
  desc: null
  value: 0.1
pop_gamma:
  desc: null
  value: 0.02
if_projector:
  desc: null
  value: 0
if_valid:
  desc: null
  value: 0
temp_tau_pop:
  desc: null
  value: 0.1
lambda_ForkMerge:
  desc: null
  value: 0.5
adaloss_mode:
  desc: null
  value: pos
train_mode:
  desc: null
  value: origin
if_adaptive:
  desc: null
  value: 1
freeze_mlp:
  desc: null
  value: 200
comment:
  desc: null
  value: _
user_emb:
  desc: null
  value: 0
item_emb:
  desc: null
  value: 0
project:
  desc: null
  value: GCLRec_No_Valid
name:
  desc: null
  value: LightGCN+AdaLoss
tag:
  desc: null
  value:
  - Adaptive_loss
notes:
  desc: null
  value: LGN_+_AdaLoss_mlp
group:
  desc: null
  value: Ours
job_type:
  desc: null
  value: gowalla
c:
  desc: null
  value: nothing
device:
  desc: null
  value: cuda
cores:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    code_path: code/code/main.py
    python_version: 3.9.13
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687746444.088841
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 1
      - 7
      - 13
      - 15
      - 16
      - 23
      4: 3.9.13
      5: 0.15.3
      8:
      - 5
    m:
    - 1: custom_epoch
      6:
      - 3
    - 1: gowalla/loss
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/recall@20
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/ndcg@20
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/precision@20
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_1@20
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_2@20
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_3@20
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_4@20
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_5@20
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_6@20
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_7@20
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_8@20
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_9@20
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_10@20
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/recall@40
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/ndcg@40
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/precision@40
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_1@40
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_2@40
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_3@40
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_4@40
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_5@40
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_6@40
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_7@40
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_8@40
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_9@40
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/groups/recall_group_10@40
      5: 1
      6:
      - 1
      - 3
    - 1: gowalla/time_cost_s
      5: 1
      6:
      - 1
      - 3
