wandb_version: 1

temp_tau:
  desc: null
  value: 0.1
latent_dim_rec:
  desc: null
  value: 64
num_layers:
  desc: null
  value: 3
dataset:
  desc: null
  value: yelp2018
lr:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 0.0001
seed:
  desc: null
  value: 2023
model:
  desc: null
  value: LightGCN
epochs:
  desc: null
  value: 500
if_multicore:
  desc: null
  value: 1
early_stop_steps:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 2048
lambda1:
  desc: null
  value: 0.1
topks:
  desc: null
  value:
  - 20
  - 40
test_u_batch_size:
  desc: null
  value: 2048
pop_group:
  desc: null
  value: 10
perplexity:
  desc: null
  value: 50
visual_epoch:
  desc: null
  value: 3
if_double_label:
  desc: null
  value: 1
if_tsne:
  desc: null
  value: 1
tsne_group:
  desc: null
  value:
  - 0
  - 9
init_method:
  desc: null
  value: Normal
tsne_points:
  desc: null
  value: 2000
loss:
  desc: null
  value: Adaptive
augment:
  desc: null
  value: 'No'
alpha:
  desc: null
  value: 0.5
centroid_mode:
  desc: null
  value: eigenvector
commonNeighbor_mode:
  desc: null
  value: SC
n_cluster:
  desc: null
  value: 10
sigma_gausse:
  desc: null
  value: 1.0
adaptive_method:
  desc: null
  value: mlp
if_visual:
  desc: null
  value: 0
if_projector:
  desc: null
  value: 0
if_valid:
  desc: null
  value: 1
adaloss_mode:
  desc: null
  value: pos
if_adaptive:
  desc: null
  value: 1
freeze_mlp:
  desc: null
  value: 500
sampling:
  desc: null
  value: uiij
comment:
  desc: null
  value: _
project:
  desc: null
  value: GCLRec_Valid
name:
  desc: null
  value: mixup
tag:
  desc: null
  value:
  - mixup
notes:
  desc: null
  value: 3InfoNCE
group:
  desc: null
  value: Ours
job_type:
  desc: null
  value: yelp2018
c:
  desc: null
  value: testing
device:
  desc: null
  value: cuda
cores:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    code_path: code/pyg_code/main.py
    python_version: 3.10.11
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689338943.656755
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 1
      - 7
      - 13
      - 15
      - 16
      - 23
      4: 3.10.11
      5: 0.15.4
      8:
      - 5
    m:
    - 1: custom_epoch
      6:
      - 3
    - 1: yelp2018/loss
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/recall@20
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/ndcg@20
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/precision@20
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_1@20
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_2@20
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_3@20
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_4@20
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_5@20
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_6@20
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_7@20
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_8@20
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_9@20
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_10@20
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/recall@40
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/ndcg@40
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/precision@40
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_1@40
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_2@40
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_3@40
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_4@40
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_5@40
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_6@40
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_7@40
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_8@40
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_9@40
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/groups/recall_group_10@40
      5: 1
      6:
      - 1
      - 3
    - 1: yelp2018/time_cost_s
      5: 1
      6:
      - 1
      - 3
